# 服务器端口号及根路径
server:
  servlet:
    context-path: /identification
  port: 6677

# 数据库连接信息
spring:
  datasource:

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/image_identification?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234

  # 配置热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署，false即不开启热部署
      additional-paths: src/main/java #指定热部署的目录
      exclude: test/**  #指定目录不更新

# 配置Mybatis-plus逻辑删除
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 1 代表已删除，不配置默认是1，也可修改配置
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0，也可修改配置
      logic-not-delete-value: 0
  type-aliases-package: com.bf.image.pojo

# 开启swagger
springfox:
  documentation:
    swagger-ui:
      enabled: true
