# 服务器端口号及根路径
server:
  servlet:
    context-path: /identification
  port: 6677

token:
  refreshTime: 604800
  secretKey: baofly913.

# 数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/image_identification?&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: Bao0319.

  # 配置热部署
  devtools:
    restart:
      enabled: true  #设置开启热部署，false即不开启热部署
      additional-paths: src/main/java #指定热部署的目录
      exclude: test/**  #指定目录不更新

  redis:
    port: 6379
    host: redis
    password: Bao0319.
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
    virtual-host: /bf
    publisher-confirm-type: correlated
    publisher-returns: true

# 配置Mybatis-plus逻辑删除
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 1 代表已删除，不配置默认是1，也可修改配置
      logic-delete-value: 1
      # 0 代表未删除，不配置默认是0，也可修改配置
      logic-not-delete-value: 0
  type-aliases-package: com.bf.image.pojo

minio:
  #自己本地服务器 minio地址以及 账号密码，和桶名。
  url: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: my-image-bucket
  defaultPictureName: default.jpg
  publicAddr: http://aifuturedxe.cn


# 开启swagger
springfox:
  documentation:
    swagger-ui:
      enabled: true
